# Generated by Django 4.1.3 on 2023-01-09 16:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0002_category_isallow_category_isdefault"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="category",
            field=models.TextField(
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_title_category",
                        message="Word should be alphanumeric",
                        regex="^[0-9a-zA-Z\\s']*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="price",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=0, message="Price cannot be less than 0"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="translation",
            name="translation",
            field=models.CharField(
                blank=True,
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_translation",
                        message="Translation should be alphabetic",
                        regex="^[a-zA-Z.\\s]*$",
                    )
                ],
            ),
        ),
    ]
