version: '3.9'

services:
  db:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_HOST_DOCKER}
      - POSTGRES_USER=${POSTGRES_USERNAME_DOCKER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS_DOCKER}
  web:
    container_name: django
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
    depends_on:
      - db
