version: "3.8"
services:
  web:
    container_name: flashcards-django
    restart: always
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/src:z
    ports:
      - "8000:8000"
