# Generated by Django 4.1.3 on 2023-01-09 16:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="current_score",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=0, message="Price cannot be less than 0"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="spend_score",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=0, message="Price cannot be less than 0"
                    )
                ],
            ),
        ),
    ]
