# Generated by Django 4.1.3 on 2022-11-19 15:19

import cards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0004_user_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.FileField(
                blank=True, null=True, upload_to=cards.models.user_directory_path
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="knowledge",
            field=models.CharField(
                choices=[("idk", "I don't know"), ("ik", "I know"), ("alt", "Almost")],
                default="idk",
                max_length=3,
            ),
        ),
    ]
