# Generated by Django 4.1.3 on 2022-11-23 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0005_user_profile_picture_alter_answer_knowledge"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="word",
            options={"ordering": ["-updated", "word"]},
        ),
        migrations.RemoveField(
            model_name="user",
            name="email",
        ),
        migrations.RemoveField(
            model_name="user",
            name="password",
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.DeleteModel(
            name="Answer",
        ),
    ]
