# Generated by Django 4.1.3 on 2023-01-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="isAllow",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="category",
            name="isDefault",
            field=models.BooleanField(default=False),
        ),
    ]
