# Generated by Django 4.1.3 on 2022-12-18 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="price",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="word",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="words",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
