# Generated by Django 4.1.3 on 2022-11-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0002_user_name_alter_user_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="name",
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
