# Generated by Django 4.1.3 on 2022-12-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0005_category_user_alter_user_score"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ranking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ranking_date", models.DateTimeField(auto_now=True)),
                ("ranking_list", models.CharField(max_length=255)),
            ],
        ),
    ]
