# Generated by Django 4.1.3 on 2022-12-24 12:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0005_remove_ranking_ranking_list_ranking_ranking_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="user",
        ),
        migrations.AddField(
            model_name="category",
            name="users",
            field=models.ManyToManyField(
                related_name="categories", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
