# Generated by Django 4.1.3 on 2022-12-06 17:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0006_ranking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ranking",
            name="ranking_list",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.IntegerField(), size=None
                ),
                size=None,
            ),
        ),
    ]
