# Generated by Django 4.1.3 on 2022-12-26 22:06

import cards.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0008_user_name_alter_user_first_name_alter_user_last_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="name",
            new_name="category",
        ),
        migrations.RemoveField(
            model_name="category",
            name="cost",
        ),
        migrations.AddField(
            model_name="category",
            name="price",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.FileField(
                blank=True, null=True, upload_to=cards.models.user_directory_path
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="status",
            field=models.CharField(
                choices=[
                    ("Wait", "Wait for acceptation"),
                    ("Accepted", "Accepted by moderator"),
                    ("Unaccepted", "Unaccepted by moderator"),
                ],
                default="Wait",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="word",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="word",
            field=models.TextField(
                blank=True, max_length=255, verbose_name="Word name"
            ),
        ),
    ]
