# Generated by Django 4.1.3 on 2022-12-29 16:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0009_rename_name_category_category_remove_category_cost_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="word",
            name="translated_word",
        ),
        migrations.AlterField(
            model_name="word",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="word",
            field=models.TextField(
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_word",
                        message="Word should be alphabetic",
                        regex="^[a-zA-Z]*$",
                    )
                ],
            ),
        ),
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "translation",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_translation",
                                message="Translation should be alphabetic",
                                regex="^[a-zA-Z]*$",
                            )
                        ],
                    ),
                ),
                ("pronunciation", models.CharField(blank=True, max_length=100)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="cards.word",
                    ),
                ),
            ],
        ),
    ]
